version: '3'
services:

  php-fpm:
    env_file:
      ./../.env
    build:
      context: ./php
      dockerfile: php-fpm.docker
    volumes:
      - ./../:/app
    depends_on:
      - db

  php-cli:
    env_file:
      ./../.env
    build:
      context: ./php
      dockerfile: php-cli.docker
    volumes:
      - ./../:/app
    tty:
      true

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./../:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: social_network
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/etc/mysql/conf.d
    ports:
      - "3306:3306"