version: '3'
services:

  php-fpm:
    env_file:
      ./../.env
    build:
      context: ./php
      dockerfile: php-fpm.docker
    volumes:
      - ./../:/app
    depends_on:
      - master
      - slave-1
      - slave-2

  php-cli:
    env_file:
      ./../.env
    build:
      context: ./php
      dockerfile: php-cli.docker
    volumes:
      - ./../:/app
    tty:
      true

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./../:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  master:
    build:
      context: ./db/master
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: social_network
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

  slave-1:
    build:
      context: ./db/slave1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: social_network
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    depends_on:
      - master

  slave-2:
    build:
      context: ./db/slave2
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: social_network
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3308:3306"
    depends_on:
      - master