version: '3'
services:

  php-fpm:
    env_file:
      ./../.env
    build:
      context: ./php
      dockerfile: php-fpm.docker
    volumes:
      - ./../:/app
    depends_on:
      - main
      - shard-1
      - shard-2

  php-cli:
    env_file:
      ./../.env
    build:
      context: ./php
      dockerfile: php-cli.docker
    volumes:
      - ./../:/app
    tty:
      true

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./../:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  main:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: social_network
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

  shard-1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: social_network
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"

  shard-2:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: social_network
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3308:3306"